app/src/main/AndroidManifest.xml

Support super widescreen Android devices

---

app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/SettingsActivity.java
app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_colors.xml
app/src/main/res/xml/pref_notification.xml

Add option to toggle notification design in N+

---

app/src/main/java/com/kabouzeid/gramophone/adapter/PlaylistAdapter.java
app/src/main/java/com/kabouzeid/gramophone/loader/LastAddedLoader.java
app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/LastAddedPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/SettingsActivity.java
app/src/main/java/com/kabouzeid/gramophone/util/CalendarUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_activity_settings.xml
app/src/main/res/xml/pref_playlists.xml

Add last added playlist interval preference

---

app/src/main/java/com/kabouzeid/gramophone/helper/MusicPlayerRemote.java
app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java

Add the queue total remaining time in the now playing screen.
Issue #157.

Queue total time (issue #157)

---

app/src/main/java/com/kabouzeid/gramophone/adapter/album/AlbumAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/album/HorizontalAlbumAdapter.java
app/src/main/java/com/kabouzeid/gramophone/glide/PhonographColoredTarget.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
app/src/main/res/menu/menu_artist_detail.xml

This will add the gradient color for the albums also on the artist page.

Add palette color of album on artist page

---

app/src/main/java/com/kabouzeid/gramophone/adapter/song/CustomPlaylistSongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/song/SongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/PlaylistDetailActivity.java
app/src/main/res/layout/activity_playlist_detail.xml

Use fast scroller for playlists

---

app/src/main/AndroidManifest.xml

Fixes https://github.com/kabouzeid/phonograph-issue-tracker/issues/99

Support LG split window

---

app/src/main/java/com/kabouzeid/gramophone/modelAndroidAuto/AutoMusicProvider.java
app/src/main/res/values/strings.xml

Remove Android Auto menu item subtitles

---

app/src/main/AndroidManifest.xml
app/src/main/res/values/styles.xml

Added a theme based on what's described on [page 7 of this PDF](http://commondatastorage.googleapis.com/androiddevelopers/shareables/auto/AndroidAuto-custom-colors.pdf).
Fixes #179.

Add Android Auto theme

---

app/src/main/java/com/kabouzeid/gramophone/dialogs/LyricsDialog.java
app/src/main/java/com/kabouzeid/gramophone/helper/MusicProgressViewUpdateHelper.java
app/src/main/java/com/kabouzeid/gramophone/model/lyrics/AbsSynchronizedLyrics.java
app/src/main/java/com/kabouzeid/gramophone/model/lyrics/Lyrics.java
app/src/main/java/com/kabouzeid/gramophone/model/lyrics/SynchronizedLyrics.java
app/src/main/java/com/kabouzeid/gramophone/model/lyrics/SynchronizedLyricsLRC.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/PlayerAlbumCoverFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/util/FileUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
app/src/main/res/layout/fragment_player_album_cover.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_now_playing_screen.xml

This adds synchronized lyrics support. Lyrics are read from file tags. Only [LRC format](https://en.wikipedia.org/wiki/LRC_(file_format)) is supported now.

Add synchronized lyrics support (only LRC format at the moment)

---

app/src/main/java/com/kabouzeid/gramophone/adapter/SearchAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/artist/ArtistAdapter.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java

Fixes #174.
@kabouzeid was there any specific reason to load full bitmap into 40dp ImageView?

Performance issue with artist images (#174)

---

app/src/main/java/com/kabouzeid/gramophone/adapter/SearchAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/artist/ArtistAdapter.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java

Reverts kabouzeid/Phonograph#223

Revert "Performance issue with artist images (#174)"

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kabouzeid/gramophone/appwidgets/AppWidgetCard.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/BaseAppWidget.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/BootReceiver.java
app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
app/src/main/res/drawable-v21/widget_selector_light.xml
app/src/main/res/drawable/card.xml
app/src/main/res/drawable/widget_selector_light.xml
app/src/main/res/layout/app_widget_card.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/app_widget_card_info.xml

Card widget

---

app/src/main/java/com/kabouzeid/gramophone/appwidgets/AppWidgetBig.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/AppWidgetCard.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/AppWidgetClassic.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/AppWidgetSmall.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/BaseAppWidget.java

Just cleaning up the code here to move the repeated things from the various child widget classes into the base class.
I suspect this will conflict with #225, so I'll wait until that's merged in first.

Refactor widget classes

---

README.md

Better README with proper license

---

app/src/main/java/com/kabouzeid/gramophone/service/notification/PlayingNotificationImpl.java
app/src/main/res/layout/notification.xml
app/src/main/res/layout/notification_big.xml

This is a followup to (the failed PR) #170.
Closes #169 and closes #149.

Default classic notification background to white

---

app/src/main/java/com/kabouzeid/gramophone/ui/activities/tageditor/SongTagEditorActivity.java
app/src/main/res/layout/activity_song_tag_editor.xml

Remove double elevation in tag editor

---

app/src/main/res/layout/activity_playlist_detail.xml

Vertically center empty playlist message

---

app/src/main/java/com/kabouzeid/gramophone/adapter/song/OrderablePlaylistSongAdapter.java

Fixes https://github.com/kabouzeid/phonograph-issue-tracker/issues/7

Allow dragging playlist items by image too

---

app/src/main/res/drawable/toolbar_gradient.xml
app/src/main/res/layout/fragment_card_player.xml
app/src/main/res/layout/shadow_statusbar_toolbar.xml
app/src/main/res/values/colors.xml

Fix toolbar scrim in album/artist detail view

---

app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/LibraryFragment.java
app/src/main/res/menu/menu_main.xml

Add back shuffle all to overflow menu

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Update Gradle for Android Studio 3.0

---

app/build.gradle
app/src/main/java/com/kabouzeid/gramophone/adapter/song/OrderablePlaylistSongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/song/PlayingQueueAdapter.java

Includes updating to support library 27.0.0.

Update advrecyclerview and target SDK 27

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kabouzeid/gramophone/adapter/GenreAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/MusicLibraryPagerAdapter.java
app/src/main/java/com/kabouzeid/gramophone/helper/SortOrder.java
app/src/main/java/com/kabouzeid/gramophone/interfaces/LoaderIds.java
app/src/main/java/com/kabouzeid/gramophone/loader/GenreLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/SongLoader.java
app/src/main/java/com/kabouzeid/gramophone/model/Genre.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/GenreDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/pager/GenresFragment.java
app/src/main/java/com/kabouzeid/gramophone/util/NavigationUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
app/src/main/res/layout/activity_genre_detail.xml
app/src/main/res/layout/item_list_simple.xml
app/src/main/res/menu/menu_genre_detail.xml
app/src/main/res/values/strings.xml

Closes #235.
This is an early WIP. Current issues:
- Genre details could show songs list and/or albums?
- Overflow menu items for genre details?
- Songs list ordering

Genres tab

---

app/build.gradle

Prevent build from crashing when no Git or on Windows

---

app/src/main/java/com/kabouzeid/gramophone/adapter/PlaylistAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/SongFileAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/album/AlbumAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/artist/ArtistAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/song/AbsOffsetSongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/song/SongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/PlaylistDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/folders/FoldersFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/pager/AbsLibraryPagerRecyclerViewCustomGridSizeFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/pager/AbsLibraryPagerRecyclerViewFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/util/Util.java
app/src/main/java/com/kabouzeid/gramophone/views/HorizontalItemDivider.java
app/src/main/res/layout/item_list.xml

I created and added a HorizontalItemDivider for the recycler view as suggested by #212 . I only added it on the folder list, but if the implementation is OK, I'll add it to the other lists as well.
As for the color of the divider, since it's set as a attr(I assume its for theming purposes), I created a helper function in the Utils.java.
Also, the original divider views are still there but are commented out for testing purposes. Obviously they will be removed in the end.

Item decorator for recycler view (#212)

---

app/src/main/java/com/kabouzeid/gramophone/adapter/GenreAdapter.java
app/src/main/java/com/kabouzeid/gramophone/loader/GenreLoader.java
app/src/main/java/com/kabouzeid/gramophone/model/Genre.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
app/src/main/res/layout/item_list_simple.xml
app/src/main/res/values/strings.xml

Potentially fixes #372 and closes #371.
I intended on removing the list of songs with no genre anyway to avoid the issue of trying to get more than 999 items in a subquery.

Remove unknown genre, add number of songs

---

app/src/main/java/com/kabouzeid/gramophone/loader/GenreLoader.java

Fixes https://github.com/kabouzeid/phonograph-issue-tracker/issues/256
Not sure if it triggers #372 though.

Only show genres with songs

---

app/src/main/java/com/kabouzeid/gramophone/model/CategoryInfo.java
app/src/main/java/com/kabouzeid/gramophone/preferences/LibraryPreferenceDialog.java

Persist library categories dialog state between invocations

---

app/build.gradle
app/src/main/assets/phonograph-changelog.html
app/src/main/java/com/kabouzeid/gramophone/ui/activities/AboutActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/NavigationUtil.java
app/src/main/res/drawable/ic_album_white_24dp.xml
app/src/main/res/layout/activity_album_detail.xml
app/src/main/res/layout/activity_artist_detail.xml
app/src/main/res/layout/card_special_thanks.xml
app/src/main/res/values-land/dimens.xml
app/src/main/res/values-sw600dp-land/dimens.xml
app/src/main/res/values-sw600dp/dimens.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

Redesigned the album page
See https://github.com/kabouzeid/Phonograph/issues/478

Redesigned album and artist detail page

---

app/build.gradle
app/src/main/AndroidManifest.xml

Now that APIs have been finalised as of P Preview 3 (P Beta 2), app can target SDK 28 successfully.

App target updated to SDK 28 (Android P)

---

app/src/main/java/com/kabouzeid/gramophone/ui/activities/MainActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/AbsMainActivityFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/folders/FoldersFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/LibraryFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/views/StatusBarMarginFrameLayout.java
app/src/main/java/com/kabouzeid/gramophone/views/StatusBarView.java
app/src/main/res/layout-land/fragment_card_player.xml
app/src/main/res/layout-land/fragment_flat_player.xml
app/src/main/res/layout/activity_main_content.xml
app/src/main/res/layout/activity_main_drawer_layout.xml
app/src/main/res/layout/fragment_card_player.xml
app/src/main/res/layout/fragment_flat_player.xml
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_library.xml
app/src/main/res/layout/shadow_statusbar_toolbar.xml
app/src/main/res/layout/status_bar.xml
build.gradle

This is notch support via WindowInsets. I've tested it with KitKat, Lollipop and Pie. Still needs to be tested on API 16.

Notch support via WindowInsets

---

app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/NotRecentlyPlayedPlaylist.java
app/src/main/res/drawable/ic_watch_later_black_24dp.xml
app/src/main/res/drawable/ic_watch_later_white_24dp.xml

A poor man's attempt to convey the fact that the Not recently played list is a mirror of the Recently played/History list
I.e. with an inverted icon

Change the icon of the Not recently played playlist

---

app/src/main/java/com/kabouzeid/gramophone/adapter/SearchAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/album/AlbumAdapter.java
app/src/main/java/com/kabouzeid/gramophone/adapter/song/SongAdapter.java
app/src/main/java/com/kabouzeid/gramophone/appwidgets/base/BaseAppWidget.java
app/src/main/java/com/kabouzeid/gramophone/model/AbsCustomPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/HistoryPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/LastAddedPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/NotRecentlyPlayedPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/service/notification/PlayingNotificationImpl24.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/MainActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/AbsPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java

Populate album name / artist name / song counts across different view as "subtitle" that enriches the main info displayed in the title.
This includes the notification, different list-based views, the main menu, the now-playing view, search result...
For example, the included images show the added annotations highlighted with white underline

Library annotations

---

app/src/main/java/com/kabouzeid/gramophone/helper/menu/SongMenuHelper.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/RingtoneManager.java
app/src/main/res/values/strings.xml

this is a resubmission of #663 rebased to the latest HEAD

Fix ringtone sharing

---

app/src/main/java/com/kabouzeid/gramophone/ui/activities/AboutActivity.java
app/src/main/res/layout/card_special_thanks.xml
app/src/main/res/values/donottranslate.xml

Fixes #688  
Tested manually on Android 9.0

Remove Google Plus links and add alternate links

---

app/src/main/java/com/kabouzeid/gramophone/dialogs/CreatePlaylistDialog.java
app/src/main/java/com/kabouzeid/gramophone/loader/AlbumLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/ArtistLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/GenreLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/PlaylistLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/PlaylistSongLoader.java
app/src/main/java/com/kabouzeid/gramophone/loader/SongLoader.java
app/src/main/java/com/kabouzeid/gramophone/model/AbsCustomPlaylist.java
app/src/main/java/com/kabouzeid/gramophone/model/Album.java
app/src/main/java/com/kabouzeid/gramophone/model/Artist.java
app/src/main/java/com/kabouzeid/gramophone/model/Genre.java
app/src/main/java/com/kabouzeid/gramophone/model/Playlist.java
app/src/main/java/com/kabouzeid/gramophone/model/PlaylistSong.java
app/src/main/java/com/kabouzeid/gramophone/model/Song.java
app/src/main/java/com/kabouzeid/gramophone/provider/MusicPlaybackQueueStore.java
app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/kabouzeid/gramophone/ui/activities/MainActivity.java
app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/NavigationUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/PlaylistsUtil.java
app/src/main/java/com/kabouzeid/gramophone/util/RingtoneManager.java

Credit to @linucksrox for starting this work on getting the app to load in Android 11 in PR #869
Closes #849

Fix issues on Android 11
