- app/src/main/java/com/kabouzeid/gramophone/ui/activities/tageditor/AbsTagEditorActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/tageditor/SongTagEditorActivity.java
- app/src/main/res/layout/activity_song_tag_editor.xml
- app/src/main/res/values/strings.xml
Allow to edit lyrics on the tag editor activity. I've tested it with .mp3 and .m4a files
> Add lyrics editor in SongTagEditorActivity

- app/src/main/AndroidManifest.xml
Removing it caused the inability to start playback if the ui was not in
foreground
> Add MediaButtonIntentReceiver back into AndroidManifest

- app/src/main/java/com/kabouzeid/gramophone/appshortcuts/AppShortcutLauncherActivity.java
- app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/ShuffleAllPlaylist.java
- app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
- app/src/main/res/values/strings.xml
Fixes issue #111 .
```play()``` was still called even if the playlist was empty.
This adds a check for that and shows a toast if it is.
Thanks @arkon!
> Fix: App shortcut: Crash and resume when empty (issue #111 and issue #112)

- app/src/main/java/com/kabouzeid/gramophone/helper/MusicPlayerRemote.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/MainActivity.java
Address issue #100
When media file is selected from various file browers, the uri sent to app might be different scheme like file or content. Fix is to query the media file based on different scheme.
Tested on Android 7.1.1 from ASUS File Manager, Amaze and Android Download.
> Fix: can't play media files from file browser

- app/src/main/java/com/kabouzeid/gramophone/util/MusicUtil.java
This is sort of a follow-up to #162.
"Fixes" formatting of readable duration strings so it shows hours separately (e.g. 1:02:31 instead of 62:31).
> Format hours in readable duration string

- app/src/main/java/com/kabouzeid/gramophone/ui/activities/AboutActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/AlbumDetailActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/ArtistDetailActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/PlaylistDetailActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/SearchActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/activities/SettingsActivity.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/folders/FoldersFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/LibraryFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java
- app/src/main/java/com/kabouzeid/gramophone/util/Util.java
- app/src/main/java/com/kabouzeid/gramophone/util/ViewUtil.java
- app/src/main/res/layout/shadow_statusbar_toolbar.xml
This fixes issues on devices which have non-standard status bar sizes (i.e. not multiples of 24dp), notably, some Android head units, which have a larger status bar at the top of the screen.
It simply figures out the size of the statusbar at runtime, and resizes the statusbar view in all relevant activities/fragments to ensure the view is not drawing underneath the statusbar.
> Dynamic size status bars

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/folders/FoldersFragment.java
Previously any vorbis files (or any other format using the Ogg container) were missing from the folders view.
This is because the Android mime type for .ogg is "application/ogg" rather than "audio/ogg". This pull request simply adds an additional check for this.
> Modified audioFileFilter to recognise .ogg files.

- app/src/main/res/layout/app_widget_big.xml
- app/src/main/res/layout/app_widget_classic.xml
- app/src/main/res/layout/app_widget_small.xml
- app/src/main/res/layout/fragment_card_player_playback_controls.xml
- app/src/main/res/layout/fragment_flat_player_playback_controls.xml
Closes https://github.com/kabouzeid/phonograph-issue-tracker/issues/34.
Tested with Arabic. This is a fix for both now playing screen layouts and the 3 widgets. Note that this likely doesn't work in Android 4.1 since `android:layoutDirection` is API 17+.
> Fix previous/next button order for RTL languages

- app/build.gradle
For example, it'll say "0.15.0 DEBUG (version-name-branch)". I just wanted to add this since I often forget which branch's build I have on my device.
> Add git branch name to debug app's version name

- app/src/main/java/com/kabouzeid/gramophone/ui/activities/bugreport/BugReportActivity.java
Closes https://github.com/kabouzeid/phonograph-issue-tracker/issues/160
See https://stackoverflow.com/a/40393909 for more information. The alternative is to use an `EditText` so that the parent is correct, but that relies on knowing how it works internally which is evidently prone to failure, so I'd rather just directly reference the layout IDs.
> Fix crash when using GitHub issue form

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerPlaybackControlsFragment.java
Closes #101.
I originally wanted to modify `addAnimation` so it would go from `view.getScaleX()`/`view.getScaleY()` to `1f`, but it seems the end value is set as `0f` despite it animating to `1f`. On a similar note, `prepareForAnimation` doesn't actually seem necessary, as the views' scales implicitly get set to `0f` when the `Animator`s are set anyway. I wasn't sure if it was required for some reason though.
> Prevent flat controls from animating on every show

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/AbsPlayerFragment.java
- app/src/main/res/menu/menu_player.xml
- app/src/main/res/values/strings.xml
Adds a menu item to the now playing screen to save the current queue as a new playlist.
Closes https://github.com/kabouzeid/phonograph-issue-tracker/issues/6
> Save current playing queue as playlist

- app/build.gradle
- app/src/main/java/com/kabouzeid/gramophone/service/notification/PlayingNotification.java
- app/src/main/java/com/kabouzeid/gramophone/service/notification/PlayingNotificationImpl.java
- app/src/main/java/com/kabouzeid/gramophone/service/notification/PlayingNotificationImpl24.java
This is currently blocked by https://github.com/h6ah4i/android-advancedrecyclerview/issues/396.
We should also consider using the native `fastScrollEnabled` flag for `RecyclerView`s ([see changelog](https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-0) for more info).
> [WIP] Update support libs and build tools to v26

- app/src/main/java/com/kabouzeid/gramophone/ui/activities/PlaylistDetailActivity.java
- app/src/main/java/com/kabouzeid/gramophone/util/PlaylistsUtil.java
- app/src/main/res/menu/menu_playlist_detail.xml
- app/src/main/res/values/strings.xml
Closes #232.
- Adds "Play", "Add to playing queue", "Rename", "Delete", and "Save as file" to the playlist detail activity view
- Renaming the playlist updates the name in the activity
- Deleting the playlist exits out of it
There's no logic to deal with Favorites though. I think Favorites should be converted into a special playlist that appears at the top of the list (with Last added, History, and My top tracks), but can't be renamed/deleted.
> Add menu actions to playlist detail activity

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/AbsPlayerFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/PlayerAlbumCoverFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java
- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/flat/FlatPlayerFragment.java
- app/src/main/res/drawable/toolbar_gradient.xml
- app/src/main/res/layout/fragment_card_player.xml
- app/src/main/res/layout/fragment_flat_player.xml
- app/src/main/res/layout/navigation_drawer_header.xml
- app/src/main/res/layout/shadow_statusbar_toolbar.xml
- app/src/main/res/layout/shadow_toolbar.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
Fixes #69.
Improved protection shadow for the status/toolbar in portrait player layouts, and also increased the height of the scrim for the navigation menu's album art text so it works better.
Also added the ability to single-tap the album art in the player to toggle the visibility of the toolbar (and its scrim).
> Improve toolbar scrim

- app/src/main/java/com/kabouzeid/gramophone/helper/MusicPlayerRemote.java
When clicking on music files in some file exploring apps, Phonograph opens but does nothing, because there is `Uri.getPath()` does not return a real file path. This change allows Phonograph to open and play for some file explorers that it couldn't previously (Samsung's "My Files" being a big one). 
It still doesn't work for some Uri's, like ones from Astro Explorer. Ideally it'd use `ContentResolver` to get a `FileDescriptor` for these Uri's and open that in the `MediaPlayer`, but that looks like a major change.
> Try to get file path from DATA column of Uri

- app/src/main/java/com/kabouzeid/gramophone/adapter/album/HorizontalAlbumAdapter.java
If the year of the Album has not a valid value (i.e. year <= 0), do not use it in the Album text.
This fixes issues #121 and #355
> Fix album with year "0" - Issues #121 and #355

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/LibraryFragment.java
Right now the pager does not remain hidden after restarting phonograph.
Hiding the tabs when setting up the view pager makes the change to persist between runs.
> Always hide single-tab pager

- app/src/main/java/com/kabouzeid/gramophone/preferences/NowPlayingScreenPreferenceDialog.java
The page indicator was stuck on the first page without knowing that the preference was changed. Now we let the page indicator know that we had a change of heart
This fixes #408
> Move Pageindicator to current position

- app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
Many heatsets can switch track with long click on volume buttons. Two long clicks requires around 5 seconds. With 2 seconds soooo hard to do this.
> FIX: Can't swich to previous track with long click

- app/src/main/java/com/kabouzeid/gramophone/adapter/album/HorizontalAlbumAdapter.java
- app/src/main/java/com/kabouzeid/gramophone/glide/audiocover/AudioFileCoverFetcher.java
This fixes some broken images on the manual scan with a couple additions to the album cover search filter. I also modified the horizontal album adapter so an unknown year value will match the album view details.
> fix png files not loading

- app/src/main/java/com/kabouzeid/gramophone/ui/fragments/mainactivity/library/LibraryFragment.java
- app/src/main/java/com/kabouzeid/gramophone/util/PlaylistsUtil.java
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
It's great that Phonograph already lets users save individual playlists as M3U files, but when one is really invested in the whole playlist thing and ends up with 69 of them like me, going through them individually to manually back them up is a bit of a hassle.
This adds an item to the options menu of the library when the playlists tab is visible, which lets the user export all playlists at once. I thought about integrating this into the multiselection to give more fine grained control over which playlists are saved, but since it's not currently possible to select all items with once click, the user would still have to select 69 items by hand in my case. So I ended up just adding the option to export all playlists, which is a pretty minor change.
> Bulk playlist export

- app/src/main/java/com/kabouzeid/gramophone/helper/MusicPlayerRemote.java
- app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_audio.xml
An option to turn sticky shuffle on or off. It's enabled by default so it keeps the current functionality the same. I noticed every other player has it so hopefully you don't have any issues with it being in the app.
> Added preference to turn off shuffle mode when selecting new list of songs

- app/build.gradle
- app/src/main/java/com/kabouzeid/gramophone/glide/audiocover/AudioFileCoverFetcher.java
I noticed that embedded album art exceeding some size is not displayed. While looking into it, I noticed the following in the log.
```
? E/ID3: skipping huge ID3 metadata of size 3337734
com.kabouzeid.gramophone.debug E/MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed because the ID3 tag is too big
```
A quick search revealed that the code responsible for reading ID3 tags in Android's Stagefright component skips tags larger than 3 MiB. You can see that on line 31 in the [source file](http://www.androidcodesearch.com/source/frameworks/av/media/libstagefright/id3/ID3.cpp).
The result is that the MediaStore won't deliver the album art. But the problem persists even when _Ignore Media Store covers_ is enabled, because the platform's MediaMetadataReceiver, which …
> Fix loading of large embedded album art

- app/src/main/res/values/donottranslate.xml
Since they're in `donottranslate.xml`, probably they should also be `translatable="false"` :)
"Card" and "Flat" (presumably for the Now Playing screen layout types) are also in `donottranslate.xml` but are not marked as `translatable="false"` – should they be? I can add them to this PR if so.
> Mark names as not translatable

- app/src/main/java/com/kabouzeid/gramophone/adapter/PlaylistAdapter.java
- app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/AbsSmartPlaylist.java
- app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/LastAddedPlaylist.java
- app/src/main/java/com/kabouzeid/gramophone/model/smartplaylist/NotRecentlyPlayedPlaylist.java
As of the case of LastAddedItem, the Clear action on the playlist NotRecentlyPlayed is not make sense.
This PR remove it from the popup menu.
Some refactoring is done on the playlist popup menu builder, to isolate plain playlist menu code from smart ones.
> Disable clear menu item on NotRecentlyPlayed

- app/src/main/java/com/kabouzeid/gramophone/dialogs/SleepTimerDialog.java
- app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
- app/src/main/java/com/kabouzeid/gramophone/util/PreferenceUtil.java
- app/src/main/res/layout/dialog_sleep_timer.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Implement #329.
This commit adds a CheckBox to dialog_sleep_timer, and a curresponding
option `TIMER_FINISH_MUSIC` in PreferenceUtil.
In MusicService, a new flag `pendingQuit` is to indicate if it should
stop after current music stops. A new action `ACTION_PENDING_QUIT` will
set that flag.
Canceling is a little tricky. I must bind MusicService in Dialog
activity to check if `pendingQuit` is set, and show the corresponding
canceling button.
> Finish current music when Sleep Timer stops

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
Lot of the open issues are about issues on Android 10, namely storage issues and the seekbar on notification.
The notification seekbar is addressed by this [commit](https://github.com/kabouzeid/Phonograph/commit/071723a150df9fdc3017ad1e7c3df0d78b998ec5)
The storage issue is related to Scoped Storage, opting out of which is done by [this](https://github.com/kabouzeid/Phonograph/commit/aa979888ef82ee461b8a687bc4b68b106f97344a) commit. This is only a temporary solution. Better solution.
Also, another method to address the issues, is to revert to targeting SDK version of 28.
> Support Android 10, atleast for now

- app/src/main/java/com/kabouzeid/gramophone/service/MusicService.java
Fix pending quit not working if gapless playback is enabled
> Fix pending quit
